export const heroList = ["Ana", "Ashe", "Baptiste", "Bastion", "D-va", "Doomfist", "Genji", "Hanzo", "Junkrat", "Lucio",
    "McCree", "Mei", "Mercy", "Moira", "Orisa", "Pharah", "Reaper", "Reinhardt", "Roadhog", "Soldier-76",
    "Sombra", "Symmetra", "Torbjorn", "Tracer", "Widowmaker", "Winston", "Wrecking-ball", "Zarya", "Zenyatta"];

export const heroCategoryList =
    [
        { name: "Ana", type: 'SUPPORT'},
        { name: "Ashe", type: 'DAMAGE'},
        { name: "Baptiste",type: 'SUPPORT'},
        { name: "Bastion",type: 'DAMAGE'},
        { name: "D-va",type: 'TANK'},
        { name: "Doomfist",type: 'DAMAGE'},
        { name: "Genji",type: 'DAMAGE'},
        { name: "Hanzo",type: 'DAMAGE'},
        { name: "Junkrat",type: 'DAMAGE'},
        { name: "Lucio",type: 'SUPPORT'},
        { name: "McCree",type: 'DAMAGE'},
        { name: "Mei",type: 'DAMAGE'},
        { name: "Mercy",type: 'SUPPORT'},
        { name: "Moira",type: 'SUPPORT'},
        { name: "Orisa",type: 'TANK'},
        { name: "Pharah",type: 'DAMAGE'},
        { name: "Reaper",type: 'DAMAGE'},
        { name: "Reinhardt",type: 'TANK'},
        { name: "Roadhog",type: 'TANK'},
        { name: "Soldier-76",type: 'DAMAGE'},
        { name: "Sombra",type: 'DAMAGE'},
        { name: "Symmetra",type: 'DAMAGE'},
        { name: "Torbjorn",type: 'DAMAGE'},
        { name: "Tracer",type: 'DAMAGE'},
        { name: "Widowmaker",type: 'DAMAGE'},
        { name: "Winston",type: 'TANK'},
        { name: "Wrecking-ball",type: 'TANK'},
        { name: "Zarya",type: 'TANK'},
        { name: "Zenyatta",type: 'SUPPORT'},
    ];